apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aline-mysql
    spec:
      containers:
        - image: mysql:latest
          name: aline-mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: aline-mysql
spec:
  type: ClusterIP
  selector:
    app: aline-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
