apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-gateway
  template:
    metadata:
      labels:
        app: aline-gateway
    spec:
      containers:
        - name: aline-gateway
          imagePullPolicy: IfNotPresent
          image: aline_gateway:v10
          ports:
            - containerPort: 8080
          env:
            - name: APP_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: APP_SERVICE_HOST
            - name: PORTAL_LANDING
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: PORTAL_LANDING
            - name: PORTAL_DASHBOARD
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: PORTAL_DASHBOARD
            - name: PORTAL_ADMIN
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: PORTAL_ADMIN

---

apiVersion: v1
kind: Service
metadata:
  name: aline-gateway
spec:
  selector:
    app: aline-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
