apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Alinep@ssword1
  MYSQL_DATABASE: aline_db
  MYSQL_USER: aline
  MYSQL_PASSWORD: alinepassword

---

apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
stringData:
  APP_PORT: '8080'
  APP_SERVICE_HOST: http://host.docker.internal
  PORTAL_LANDING: http://localhost:3007
  PORTAL_DASHBOARD: http://localhost:4200
  PORTAL_ADMIN: http://localhost:3000

---

apiVersion: v1
kind: Secret
metadata:
  name: admin-portal-secrets
type: Opaque
stringData:
  EXTEND_ESLINT: 'true'
  REACT_APP_API_BASEURL: http://localhost:8080
  REACT_APP_TOKEN_NAME: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.K8Uib5NFJpJYoElicfpc-X9LKonAldzGgEQ81IyIu1s
  REACT_APP_BROKER_URL: http://localhost:3000

---

apiVersion: v1
kind: Secret
metadata:
  name: landing-portal-secrets
type: Opaque
stringData:
  REACT_APP_MEMBER_DASHBOARD_URL: http://localhost:4200
  REACT_APP_API: http://localhost:8080

---

apiVersion: v1
kind: Secret
metadata:
  name: member-dashboard-secrets
type: Opaque
stringData:
  api: http://localhost:8080/api
  landingPortal: http://localhost:3007
