apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-portal
  template:
    metadata:
      labels:
        app: landing-portal
    spec:
      containers:
        - name: landing-portal
          image: aline_landing_portal:v9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3007
          env:
            - name: REACT_APP_MEMBER_DASHBOARD_URL
              valueFrom:
                secretKeyRef:
                  name: landing-portal-secrets
                  key: REACT_APP_MEMBER_DASHBOARD_URL
            - name: REACT_APP_API
              valueFrom:
                secretKeyRef:
                  name: landing-portal-secrets
                  key: REACT_APP_API

---
apiVersion: v1
kind: Service
metadata:
  name: landing-portal
spec:
  selector:
    app: landing-portal
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 80
  type: LoadBalancer
