apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-micro
  template:
    metadata:
      labels:
        app: user-micro
    spec:
      containers:
        - name: user-micro
          image: user_micro:v5
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: aline-mysql
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: user-micro
spec:
  type: LoadBalancer
  selector:
    app: user-micro
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
