apiVersion: v1
kind: Secret
metadata:
  name: aws-rds-secrets
type: Opaque
stringData:
  DB_HOST: aline-db-mm.c9aaakygudzw.us-east-1.rds.amazonaws.com
  DB_NAME: alineDBmm
  DB_USERNAME: aline_admin
  DB_PASSWORD: Aline123
  DB_PORT: '3306'

---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
stringData:
  APP_PORT: '8080'
  APP_SERVICE_HOST: http://app-service-host-aws.default.svc.cluster.local
  PORTAL_LANDING: http://k8s-ingressmm-795bef71bb-2078795439.us-east-1.elb.amazonaws.com:3007
  PORTAL_DASHBOARD: http://k8s-ingressmm-795bef71bb-2078795439.us-east-1.elb.amazonaws.com:4200
  PORTAL_ADMIN: http://k8s-ingressmm-795bef71bb-2078795439.us-east-1.elb.amazonaws.com:3000
