apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-micro
  template:
    metadata:
      labels:
        app: account-micro
        target: microservice
    spec:
      containers:
        - name: account-micro
          image: 767397723308.dkr.ecr.us-east-1.amazonaws.com/aline-financial-mm:account_micro-v2
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: aws-rds-secrets
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-rds-secrets
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aws-rds-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-rds-secrets
                  key: DB_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: aws-rds-secrets
                  key: DB_PORT
          ports:
            - containerPort: 8072
---
apiVersion: v1
kind: Service
metadata:
  name: account-micro
spec:
  type: ClusterIP
  selector:
    app: account-micro
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
