apiVersion: v1
kind: Secret
metadata:
  name: aws-rds-secrets
type: Opaque
stringData:
  DB_HOST: aline-db-mm.c9aaakygudzw.us-east-1.rds.amazonaws.com
  DB_NAME: alineDBmm
  DB_USERNAME: aline_admin
  DB_PASSWORD: Aline123
  DB_PORT: '3306'

---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
stringData:
  APP_PORT: '8080'
  APP_SERVICE_HOST: http://app-service-host-aws.default.svc.cluster.local
  PORTAL_LANDING: http://aa426776ae0fb448fb1e99b5d8ef0b96-1591259611.us-east-1.elb.amazonaws.com:3007
  PORTAL_DASHBOARD: http://a6e0ba54e447c4735b62deb6620499cf-2020593779.us-east-1.elb.amazonaws.com:4200
  PORTAL_ADMIN: http://a18d4469e23a548e6a588d3f42cbc1a6-46296294.us-east-1.elb.amazonaws.com:3000

